# Generated by Django 5.2.3 on 2025-06-11 23:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Marshall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_name', models.CharField(max_length=25)),
                ('agility', models.IntegerField(default=3)),
                ('cunning', models.IntegerField(default=4)),
                ('spirit', models.IntegerField(default=2)),
                ('strength', models.IntegerField(default=2)),
                ('lore', models.IntegerField(default=1)),
                ('luck', models.IntegerField(default=3)),
                ('initiative', models.IntegerField(default=4)),
                ('range_to_hit', models.IntegerField(default=4)),
                ('melee_to_hit', models.IntegerField(default=4)),
                ('combat', models.IntegerField(default=2)),
                ('max_grit', models.IntegerField(default=2)),
                ('health', models.IntegerField(default=10)),
                ('defence', models.IntegerField(default=3)),
                ('sanity', models.IntegerField(default=10)),
                ('willpower', models.IntegerField(default=4)),
                ('character_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
