# Generated by Django 5.2.3 on 2025-06-12 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0004_remove_ranger_character_user_character_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='agility',
        ),
    ]
