# Generated by Django 5.2.3 on 2025-06-12 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0005_remove_character_agility'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='combat',
        ),
        migrations.RemoveField(
            model_name='character',
            name='cunning',
        ),
        migrations.RemoveField(
            model_name='character',
            name='defence',
        ),
        migrations.RemoveField(
            model_name='character',
            name='health',
        ),
        migrations.RemoveField(
            model_name='character',
            name='initiative',
        ),
        migrations.RemoveField(
            model_name='character',
            name='lore',
        ),
        migrations.RemoveField(
            model_name='character',
            name='luck',
        ),
        migrations.RemoveField(
            model_name='character',
            name='melee_to_hit',
        ),
        migrations.RemoveField(
            model_name='character',
            name='range_to_hit',
        ),
        migrations.RemoveField(
            model_name='character',
            name='sanity',
        ),
        migrations.RemoveField(
            model_name='character',
            name='spirit',
        ),
        migrations.RemoveField(
            model_name='character',
            name='strength',
        ),
        migrations.RemoveField(
            model_name='character',
            name='willpower',
        ),
    ]
