# Generated by Django 5.2.3 on 2025-06-12 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0006_remove_character_combat_remove_character_cunning_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='character_class',
            field=models.CharField(choices=[('Marshal', 'Marshal'), ('Rancher', 'Rancher')], default='Marshal'),
        ),
    ]
