# Generated by Django 5.2.3 on 2025-06-13 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0008_alter_character_character_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='character_class',
            field=models.CharField(choices=[('Marshal', 'Marshal'), ('Rancher', 'Rancher'), ('LawMan', 'LawMan'), ('PianoPlayer_SaloonGirl', 'PianoPlayer_SaloonGirl'), ('IndianScout', 'IndianScout'), ('Bandido', 'Bandido'), ('Preacher', 'Preacher'), ('GunSlinger', 'GunSlinger')], default='Marshal'),
        ),
    ]
