# Generated by Django 5.2.3 on 2025-06-14 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0010_passive_buff'),
    ]

    operations = [
        migrations.AddField(
            model_name='passive_buff',
            name='name',
            field=models.CharField(default='buff name here'),
        ),
        migrations.AlterField(
            model_name='passive_buff',
            name='text',
            field=models.TextField(default='text here'),
        ),
    ]
