# Generated by Django 5.2.3 on 2025-06-14 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0011_passive_buff_name_alter_passive_buff_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passive_buff',
            name='assigned_to_character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passive_buffs', to='characters.character'),
        ),
    ]
