# Generated by Django 5.2.3 on 2025-06-15 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0012_alter_passive_buff_assigned_to_character'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='current_health',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='current_sanity',
            field=models.IntegerField(default=0),
        ),
    ]
