# Generated by Django 5.2.3 on 2025-06-21 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0013_character_current_health_character_current_sanity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='current_health',
        ),
        migrations.RemoveField(
            model_name='character',
            name='current_sanity',
        ),
    ]
