# Generated by Django 5.2.3 on 2025-06-21 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0014_remove_character_current_health_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='current_health',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='current_sanity',
            field=models.IntegerField(default=0),
        ),
    ]
