# Generated by Django 5.2.3 on 2025-06-24 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0015_character_current_health_character_current_sanity'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='class_card',
            field=models.IntegerField(default=1),
        ),
    ]
