# Generated by Django 5.2.3 on 2025-06-25 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0016_character_class_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='current_grit',
            field=models.IntegerField(default=2),
        ),
    ]
