# Generated by Django 5.2.3 on 2025-06-25 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0017_character_current_grit'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='corruption',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='character',
            name='current_corruption',
            field=models.IntegerField(default=0),
        ),
    ]
