# Generated by Django 5.2.3 on 2025-06-27 03:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0018_character_corruption_character_current_corruption'),
    ]

    operations = [
        migrations.CreateModel(
            name='Side_Bag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_to_character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='side_bag', to='characters.character')),
            ],
        ),
    ]
