# Generated by Django 5.2.3 on 2025-06-30 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0020_side_bag_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='dark_stone',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='gold',
            field=models.IntegerField(default=0),
        ),
    ]
