# Generated by Django 5.2.3 on 2025-07-01 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0021_character_dark_stone_character_gold'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='level',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='character',
            name='xp',
            field=models.IntegerField(default=0),
        ),
    ]
