# Generated by Django 5.2.3 on 2025-07-01 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0022_character_level_character_xp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='character_class',
            field=models.CharField(choices=[('Marshal', 'Marshal'), ('Rancher', 'Rancher'), ('LawMan', 'LawMan'), ('PianoPlayer', 'PianoPlayer'), ('IndianScout', 'IndianScout'), ('Bandido', 'Bandido'), ('Preacher', 'Preacher'), ('GunSlinger', 'GunSlinger')], default='Marshal'),
        ),
    ]
