# Generated by Django 5.2.3 on 2025-07-01 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0023_alter_character_character_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='Per_Adventure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='buff name here')),
                ('text', models.TextField(default='text here')),
                ('assigned_to_character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='per_adventure', to='characters.character')),
            ],
        ),
        migrations.CreateModel(
            name='Per_Fight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='buff name here')),
                ('text', models.TextField(default='text here')),
                ('assigned_to_character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='per_fight', to='characters.character')),
            ],
        ),
        migrations.CreateModel(
            name='Per_Turn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='buff name here')),
                ('text', models.TextField(default='text here')),
                ('assigned_to_character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='per_turn', to='characters.character')),
            ],
        ),
    ]
