# Generated by Django 5.2.3 on 2025-07-01 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0025_alter_side_bag_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='side_bag',
            options={},
        ),
    ]
