# Generated by Django 5.2.3 on 2025-07-01 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0026_alter_side_bag_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='current_weight',
            field=models.IntegerField(default=0),
        ),
    ]
