# Generated by Django 5.2.3 on 2025-07-01 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0027_character_current_weight'),
        ('equipment', '0002_gear'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character_Gear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_to_character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equiped_gear', to='characters.character')),
                ('gear', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='character_gear', to='equipment.gear')),
            ],
        ),
    ]
