# Generated by Django 5.2.3 on 2025-07-05 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0028_character_gear'),
    ]

    operations = [
        migrations.AddField(
            model_name='character_gear',
            name='equiped',
            field=models.BooleanField(default=False),
        ),
    ]
