# Generated by Django 5.2.3 on 2025-07-08 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0029_character_gear_equiped'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='agility',
            field=models.IntegerField(default=0),
        ),
    ]
