# Generated by Django 5.2.3 on 2025-07-08 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0031_character_combat_character_cunning_character_defence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='character_init',
            field=models.BooleanField(default=False),
        ),
    ]
