# Generated by Django 5.2.3 on 2025-07-10 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0032_character_character_init'),
        ('equipment', '0007_mine_artifact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character_Mine_Artifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equiped', models.BooleanField(default=False)),
                ('assigned_to_character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equiped_mine_artifact', to='characters.character')),
                ('mine_artifact', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='character_mine_artifact', to='equipment.mine_artifact')),
            ],
        ),
    ]
