# Generated by Django 5.2.3 on 2025-07-11 00:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0033_character_mine_artifact'),
        ('equipment', '0009_targa_artifact_grit_buff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character_Targa_Artifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equiped', models.BooleanField(default=False)),
                ('assigned_to_character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equiped_targa_artifact', to='characters.character')),
                ('targa_artifact', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='character_targa_artifact', to='equipment.targa_artifact')),
            ],
        ),
    ]
