# Generated by Django 5.2.3 on 2025-07-01 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Gear Name')),
                ('description', models.TextField(default='Dose stuff')),
                ('buff_type', models.CharField(choices=[('none', 'none'), ('passive', 'passive'), ('turn', 'tunr'), ('fight', 'fight'), ('adventure', 'adventure')], default='none')),
                ('weight', models.IntegerField(default=1)),
                ('value', models.IntegerField(default=0)),
                ('dark_stone', models.IntegerField(default=0)),
                ('agility_buff', models.IntegerField(default=0)),
                ('cunning_buff', models.IntegerField(default=0)),
                ('spirit_buff', models.IntegerField(default=0)),
                ('strength_buff', models.IntegerField(default=0)),
                ('lore_buff', models.IntegerField(default=0)),
                ('luck_buff', models.IntegerField(default=0)),
                ('initiative_buff', models.IntegerField(default=0)),
            ],
        ),
    ]
