# Generated by Django 5.2.3 on 2025-07-02 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_gear'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gear',
            name='buff_type',
            field=models.CharField(choices=[('none', 'none'), ('passive', 'passive'), ('turn', 'turn'), ('fight', 'fight'), ('adventure', 'adventure')], default='none'),
        ),
    ]
