# Generated by Django 5.2.3 on 2025-07-02 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0003_alter_gear_buff_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='gear',
            name='equipped',
            field=models.BooleanField(default=False),
        ),
    ]
