# Generated by Django 5.2.3 on 2025-07-03 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0004_gear_equipped'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gear',
            name='value',
            field=models.CharField(default=0),
        ),
    ]
