# Generated by Django 5.2.3 on 2025-07-05 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0005_alter_gear_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gear',
            name='equipped',
        ),
    ]
