# Generated by Django 5.2.3 on 2025-07-10 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0008_targa_artifact'),
    ]

    operations = [
        migrations.AddField(
            model_name='targa_artifact',
            name='grit_buff',
            field=models.IntegerField(default=0),
        ),
    ]
